/**
 * CHECKED-IN migration bundle — generated by `scripts/gen-migrations.ts` from
 * the drizzle-kit folders under `packages/domain/drizzle/`. Do not edit by
 * hand; re-run the generator after `drizzle-kit generate` and commit the
 * result. The lockstep test in `src/__tests__/migrations.test.ts` asserts
 * this module stays in sync with the `.sql` files on disk.
 *
 * Each entry mirrors what Drizzle's Node Turso migrator (`readMigrationFiles`
 * + `migrateAsync`) would derive from the same folder: the full `sql`, the
 * sha256 `hash` of that SQL, and `folderMillis` (Date.UTC of the folder-name
 * timestamp). `applyMigrations` records exactly those fields into the
 * `__drizzle_migrations` journal the Node migrator uses, so the on-device
 * and Node paths share one journal and re-running is idempotent from either.
 */

export interface MigrationEntry {
  /** Drizzle migration folder name, e.g. "20260722213113_pink_puck". */
  readonly name: string;
  /** Date.UTC of the folder-name timestamp; the journal's `created_at`. */
  readonly folderMillis: number;
  /** sha256 of the full migration SQL; the journal's `hash`. */
  readonly hash: string;
  /** Full migration SQL, with `--> statement-breakpoint` separators intact. */
  readonly sql: string;
}

/** All checked-in migrations, oldest first. */
export const MIGRATIONS: readonly MigrationEntry[] = [
  {
    name: "20260722213113_pink_puck",
    folderMillis: 1784755873000,
    hash: "9e21082cfa7a241cde90fd463db258843044ecb93006730b59983f3d6992dc07",
    sql: `CREATE TABLE \`bol_docs\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT,
	\`bol_number\` text NOT NULL,
	\`filename\` text NOT NULL,
	\`source\` text DEFAULT 'scan' NOT NULL,
	\`pages\` integer DEFAULT 1 NOT NULL,
	\`vendor\` text DEFAULT '' NOT NULL,
	\`po_number\` text DEFAULT '' NOT NULL,
	\`ocr_text\` text DEFAULT '' NOT NULL,
	\`line_items\` text DEFAULT '[]' NOT NULL,
	\`auto_named\` integer DEFAULT 1 NOT NULL,
	\`created_at\` text NOT NULL,
	\`storage_url\` text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`events\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT,
	\`ts\` text NOT NULL,
	\`action\` text NOT NULL,
	\`epc\` text,
	\`item_type\` text,
	\`bol_number\` text,
	\`building\` text,
	\`vendor\` text,
	\`detail\` text
);
--> statement-breakpoint
CREATE TABLE \`local_meta\` (
	\`key\` text PRIMARY KEY,
	\`value\` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`notes\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT,
	\`ts\` text NOT NULL,
	\`item_type\` text NOT NULL,
	\`bol_number\` text DEFAULT '' NOT NULL,
	\`building\` text DEFAULT '' NOT NULL,
	\`text\` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`requests\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT,
	\`item_type\` text NOT NULL,
	\`item_name\` text DEFAULT '' NOT NULL,
	\`quantity\` integer DEFAULT 1 NOT NULL,
	\`building\` text DEFAULT '' NOT NULL,
	\`jobsite\` text DEFAULT '' NOT NULL,
	\`requester\` text DEFAULT '' NOT NULL,
	\`contact\` text DEFAULT '' NOT NULL,
	\`note\` text DEFAULT '' NOT NULL,
	\`status\` text DEFAULT 'pending' NOT NULL,
	\`created_at\` text DEFAULT '' NOT NULL,
	\`handled_at\` text DEFAULT '' NOT NULL,
	\`handler_note\` text DEFAULT '' NOT NULL,
	\`order_ref\` text DEFAULT '' NOT NULL,
	\`updated_at\` text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`tags\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT,
	\`epc\` text NOT NULL UNIQUE,
	\`item_type\` text NOT NULL,
	\`item_name\` text DEFAULT '' NOT NULL,
	\`bol_number\` text DEFAULT '' NOT NULL,
	\`po_number\` text DEFAULT '' NOT NULL,
	\`building\` text DEFAULT '' NOT NULL,
	\`sector\` text DEFAULT '' NOT NULL,
	\`vendor\` text DEFAULT '' NOT NULL,
	\`sku\` text DEFAULT '' NOT NULL,
	\`mfc_date\` text DEFAULT '' NOT NULL,
	\`quantity\` integer DEFAULT 1 NOT NULL,
	\`remaining\` integer DEFAULT 1 NOT NULL,
	\`status\` text DEFAULT 'In Warehouse' NOT NULL,
	\`received_at\` text NOT NULL,
	\`delivered_at\` text DEFAULT '' NOT NULL,
	\`checkout_building\` text DEFAULT '' NOT NULL,
	\`flag\` text DEFAULT '' NOT NULL,
	\`flagged_at\` text DEFAULT '' NOT NULL,
	\`created_at\` text NOT NULL,
	\`updated_at\` text NOT NULL,
	\`bol_doc_id\` integer
);
--> statement-breakpoint
CREATE TABLE \`vendors\` (
	\`name\` text PRIMARY KEY
);
--> statement-breakpoint
CREATE INDEX \`idx_events_action\` ON \`events\` (\`action\`);--> statement-breakpoint
CREATE INDEX \`idx_events_epc\` ON \`events\` (\`epc\`);--> statement-breakpoint
CREATE INDEX \`idx_notes_group\` ON \`notes\` (\`item_type\`,\`bol_number\`,\`building\`);--> statement-breakpoint
CREATE INDEX \`idx_tags_group\` ON \`tags\` (\`item_type\`,\`bol_number\`,\`building\`);--> statement-breakpoint
CREATE INDEX \`idx_tags_status\` ON \`tags\` (\`status\`);`,
  },
  {
    name: "20260723175838_text-ids",
    folderMillis: 1784829518000,
    hash: "f5f185d6ff8a0435a6cbd8cbdac62e7545928db87797e67da20bc4c3afda2444",
    sql: `PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE \`__new_bol_docs\` (
	\`id\` text PRIMARY KEY,
	\`bol_number\` text NOT NULL,
	\`filename\` text NOT NULL,
	\`source\` text DEFAULT 'scan' NOT NULL,
	\`pages\` integer DEFAULT 1 NOT NULL,
	\`vendor\` text DEFAULT '' NOT NULL,
	\`po_number\` text DEFAULT '' NOT NULL,
	\`ocr_text\` text DEFAULT '' NOT NULL,
	\`line_items\` text DEFAULT '[]' NOT NULL,
	\`auto_named\` integer DEFAULT 1 NOT NULL,
	\`created_at\` text NOT NULL,
	\`storage_url\` text DEFAULT '' NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_bol_docs\`(\`id\`, \`bol_number\`, \`filename\`, \`source\`, \`pages\`, \`vendor\`, \`po_number\`, \`ocr_text\`, \`line_items\`, \`auto_named\`, \`created_at\`, \`storage_url\`) SELECT \`id\`, \`bol_number\`, \`filename\`, \`source\`, \`pages\`, \`vendor\`, \`po_number\`, \`ocr_text\`, \`line_items\`, \`auto_named\`, \`created_at\`, \`storage_url\` FROM \`bol_docs\`;--> statement-breakpoint
DROP TABLE \`bol_docs\`;--> statement-breakpoint
ALTER TABLE \`__new_bol_docs\` RENAME TO \`bol_docs\`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE \`__new_events\` (
	\`id\` text PRIMARY KEY,
	\`ts\` text NOT NULL,
	\`action\` text NOT NULL,
	\`epc\` text,
	\`item_type\` text,
	\`bol_number\` text,
	\`building\` text,
	\`vendor\` text,
	\`detail\` text
);
--> statement-breakpoint
INSERT INTO \`__new_events\`(\`id\`, \`ts\`, \`action\`, \`epc\`, \`item_type\`, \`bol_number\`, \`building\`, \`vendor\`, \`detail\`) SELECT \`id\`, \`ts\`, \`action\`, \`epc\`, \`item_type\`, \`bol_number\`, \`building\`, \`vendor\`, \`detail\` FROM \`events\`;--> statement-breakpoint
DROP TABLE \`events\`;--> statement-breakpoint
ALTER TABLE \`__new_events\` RENAME TO \`events\`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE \`__new_notes\` (
	\`id\` text PRIMARY KEY,
	\`ts\` text NOT NULL,
	\`item_type\` text NOT NULL,
	\`bol_number\` text DEFAULT '' NOT NULL,
	\`building\` text DEFAULT '' NOT NULL,
	\`text\` text NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_notes\`(\`id\`, \`ts\`, \`item_type\`, \`bol_number\`, \`building\`, \`text\`) SELECT \`id\`, \`ts\`, \`item_type\`, \`bol_number\`, \`building\`, \`text\` FROM \`notes\`;--> statement-breakpoint
DROP TABLE \`notes\`;--> statement-breakpoint
ALTER TABLE \`__new_notes\` RENAME TO \`notes\`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE \`__new_tags\` (
	\`id\` text PRIMARY KEY,
	\`epc\` text NOT NULL UNIQUE,
	\`item_type\` text NOT NULL,
	\`item_name\` text DEFAULT '' NOT NULL,
	\`bol_number\` text DEFAULT '' NOT NULL,
	\`po_number\` text DEFAULT '' NOT NULL,
	\`building\` text DEFAULT '' NOT NULL,
	\`sector\` text DEFAULT '' NOT NULL,
	\`vendor\` text DEFAULT '' NOT NULL,
	\`sku\` text DEFAULT '' NOT NULL,
	\`mfc_date\` text DEFAULT '' NOT NULL,
	\`quantity\` integer DEFAULT 1 NOT NULL,
	\`remaining\` integer DEFAULT 1 NOT NULL,
	\`status\` text DEFAULT 'In Warehouse' NOT NULL,
	\`received_at\` text NOT NULL,
	\`delivered_at\` text DEFAULT '' NOT NULL,
	\`checkout_building\` text DEFAULT '' NOT NULL,
	\`flag\` text DEFAULT '' NOT NULL,
	\`flagged_at\` text DEFAULT '' NOT NULL,
	\`created_at\` text NOT NULL,
	\`updated_at\` text NOT NULL,
	\`bol_doc_id\` text
);
--> statement-breakpoint
INSERT INTO \`__new_tags\`(\`id\`, \`epc\`, \`item_type\`, \`item_name\`, \`bol_number\`, \`po_number\`, \`building\`, \`sector\`, \`vendor\`, \`sku\`, \`mfc_date\`, \`quantity\`, \`remaining\`, \`status\`, \`received_at\`, \`delivered_at\`, \`checkout_building\`, \`flag\`, \`flagged_at\`, \`created_at\`, \`updated_at\`, \`bol_doc_id\`) SELECT \`id\`, \`epc\`, \`item_type\`, \`item_name\`, \`bol_number\`, \`po_number\`, \`building\`, \`sector\`, \`vendor\`, \`sku\`, \`mfc_date\`, \`quantity\`, \`remaining\`, \`status\`, \`received_at\`, \`delivered_at\`, \`checkout_building\`, \`flag\`, \`flagged_at\`, \`created_at\`, \`updated_at\`, \`bol_doc_id\` FROM \`tags\`;--> statement-breakpoint
DROP TABLE \`tags\`;--> statement-breakpoint
ALTER TABLE \`__new_tags\` RENAME TO \`tags\`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE INDEX \`idx_events_action\` ON \`events\` (\`action\`);--> statement-breakpoint
CREATE INDEX \`idx_events_epc\` ON \`events\` (\`epc\`);--> statement-breakpoint
CREATE INDEX \`idx_notes_group\` ON \`notes\` (\`item_type\`,\`bol_number\`,\`building\`);--> statement-breakpoint
CREATE INDEX \`idx_tags_group\` ON \`tags\` (\`item_type\`,\`bol_number\`,\`building\`);--> statement-breakpoint
CREATE INDEX \`idx_tags_status\` ON \`tags\` (\`status\`);`,
  },
];
