/**
 * Generates `src/migrations.ts` from the drizzle-kit migration folders under
 * `packages/domain/drizzle/`. Each migration's `migration.sql` is embedded as a
 * template literal (backticks/backslashes escaped) alongside its sha256 `hash` and
 * `folderMillis` (Date.UTC of the folder-name timestamp) — the two fields the
 * Drizzle Node migrator records in `__drizzle_migrations`. Embedding the
 * precomputed hash keeps the on-device path off `node:crypto` (unavailable in
 * React Native).
 *
 * Run after `drizzle-kit generate`:
 *   pnpm --filter @rfid/domain exec tsx scripts/gen-migrations.ts
 */
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, existsSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const drizzleDir = join(here, "..", "drizzle");
const outFile = join(here, "..", "src", "migrations.ts");

function formatToMillis(dateStr: string): number {
  const year = Number.parseInt(dateStr.slice(0, 4), 10);
  const month = Number.parseInt(dateStr.slice(4, 6), 10) - 1;
  const day = Number.parseInt(dateStr.slice(6, 8), 10);
  const hour = Number.parseInt(dateStr.slice(8, 10), 10);
  const minute = Number.parseInt(dateStr.slice(10, 12), 10);
  const second = Number.parseInt(dateStr.slice(12, 14), 10);
  return Date.UTC(year, month, day, hour, minute, second);
}

function escForTemplateLiteral(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

const migrations = readdirSync(drizzleDir)
  .filter((sub) => existsSync(join(drizzleDir, sub, "migration.sql")))
  .sort((a, b) => a.localeCompare(b))
  .map((name) => {
    const sqlPath = join(drizzleDir, name, "migration.sql");
    const sql = readFileSync(sqlPath, "utf8");
    const hash = createHash("sha256").update(sql).digest("hex");
    const folderMillis = formatToMillis(name.slice(0, 14));
    return { name, sql, hash, folderMillis };
  });

const blocks = migrations.map(
  (m) =>
    `  {\n    name: ${JSON.stringify(m.name)},\n    folderMillis: ${m.folderMillis},\n    hash: ${JSON.stringify(m.hash)},\n    sql: \`${escForTemplateLiteral(m.sql)}\`,\n  }`,
);

const body = `/**
 * CHECKED-IN migration bundle — generated by \`scripts/gen-migrations.ts\` from
 * the drizzle-kit folders under \`packages/domain/drizzle/\`. Do not edit by
 * hand; re-run the generator after \`drizzle-kit generate\` and commit the
 * result. The lockstep test in \`src/__tests__/migrations.test.ts\` asserts
 * this module stays in sync with the \`.sql\` files on disk.
 *
 * Each entry mirrors what Drizzle's Node Turso migrator (\`readMigrationFiles\`
 * + \`migrateAsync\`) would derive from the same folder: the full \`sql\`, the
 * sha256 \`hash\` of that SQL, and \`folderMillis\` (Date.UTC of the folder-name
 * timestamp). \`applyMigrations\` records exactly those fields into the
 * \`__drizzle_migrations\` journal the Node migrator uses, so the on-device
 * and Node paths share one journal and re-running is idempotent from either.
 */

export interface MigrationEntry {
  /** Drizzle migration folder name, e.g. "20260722213113_pink_puck". */
  readonly name: string;
  /** Date.UTC of the folder-name timestamp; the journal's \`created_at\`. */
  readonly folderMillis: number;
  /** sha256 of the full migration SQL; the journal's \`hash\`. */
  readonly hash: string;
  /** Full migration SQL, with \`--> statement-breakpoint\` separators intact. */
  readonly sql: string;
}

/** All checked-in migrations, oldest first. */
export const MIGRATIONS: readonly MigrationEntry[] = [
${blocks.join(",\n")},
];
`;

writeFileSync(outFile, body);
console.log(`Wrote ${outFile} with ${migrations.length} migration(s).`);
